Travis: Improve testing when Fortran is disabled
Signed-off-by: James Dinan <james.dinan@intel.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -113,13 +113,18 @@ script:
     - export OSHRUN_LAUNCHER="mpiexec.hydra"
     - cd $TRAVIS_SRC/tests-uh
     - make $TRAVIS_PAR_MAKE C_feature_tests
-    - test $SOS_DISABLE_FORTRAN || make F_feature_tests
     #- make C_feature_tests-run 2>&1 | tee uh-tests-c-feature-tests.log
     # Check for failures in the C tests
     #- if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-c-feature-tests.log; then false; else true; fi
-    #- test $SOS_DISABLE_FORTRAN || make F_feature_tests-run 2>&1 | tee uh-tests-f-feature-tests.log
-    # Check for failures in the Fortran tests
-    #- test $SOS_DISABLE_FORTRAN || if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-feature-tests.log; then false; else true; fi
+    - >
+      if [ ! $SOS_DISABLE_FORTRAN ]; then
+          make F_feature_tests;
+          if false && [ $? -ne 0 ]; then
+              make F_feature_tests-run 2>&1 | tee uh-tests-f-feature-tests.log;
+              # Check for failures in the Fortran tests
+              if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-feature-tests.log; then false; else true; fi;
+          fi;
+      fi
     - make clean
     ###
     ### Run the UH test suite (OFI)
@@ -128,13 +133,18 @@ script:
     - export OSHRUN_LAUNCHER="mpiexec.hydra"
     - cd $TRAVIS_SRC/tests-uh
     - make $TRAVIS_PAR_MAKE C_feature_tests
-    - test $SOS_DISABLE_FORTRAN || make F_feature_tests
     - make C_feature_tests-run 2>&1 | tee uh-tests-c-feature-tests.log
     # Check for failures in the C tests
     - if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-c-feature-tests.log; then false; else true; fi
-    - test $SOS_DISABLE_FORTRAN || make F_feature_tests-run 2>&1 | tee uh-tests-f-feature-tests.log
-    # Check for failures in the Fortran tests
-    - test $SOS_DISABLE_FORTRAN || if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-feature-tests.log; then false; else true; fi
+    - >
+      if [ ! $SOS_DISABLE_FORTRAN ]; then
+          make F_feature_tests;
+          if [ $? -ne 0 ]; then
+              make F_feature_tests-run 2>&1 | tee uh-tests-f-feature-tests.log;
+              # Check for failures in the Fortran tests
+              if grep "^(test_[0-9]\+) Running.*Failed$" uh-tests-f-feature-tests.log; then false; else true; fi;
+          fi;
+      fi
     - make clean
     ###
     ### Run ISx (Portals)
